name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: cd cmd/lambda
      - run: |
          $env:GOOS="linux" \
          $env:GOARCH="amd64" \
          go build -o bootstrap main.go
      - run: tar.exe -a -c -f function.zip bootstrap

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::942343727300:role/lambda-update_wild-heart-detroit-api
          aws-region: us-east-1

      - run: |
          aws lambda update-function-code \
            --function-name wild-heart-detroit-api \
            --zip-file fileb://function.zip
